Repository ESGForumWebSiteDev/project_ESGForumWebSiteDev_laravel-deployment-repo, pull requests merged in 2023-09, with the labels that each got.

#23 feat(models): add $keyType property to User model
  app/Models/User.php
Labels: 🔨 Refactor

#21 feat(file): add file logic
  app/Http/Controllers/PostController.php
  app/Http/Controllers/SeminarController.php
  app/Models/File.php
  routes/api.php
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#24 feat(aboutus/greetings): Add information about the chairman to aboutus/greetings
  app/Http/Controllers/AboutUsController.php
  app/Models/AboutUs.php
  database/migrations/2023_09_03_115105_add_chairman_to_forum_introduce_table.php
Labels: ✨ Feature, 🔨 Refactor

#27 feat: Update users table migration to drop and recreate schema
  app/Http/Controllers/CommitteeController.php
  app/Http/Controllers/MemberController.php
  app/Http/Controllers/UserController.php
  app/Models/Member.php
  app/Models/User.php
  database/migrations/2023_09_05_122358_drop_users_table.php
  database/migrations/2023_09_05_122626_add_columns_members_table.php
  routes/api.php
Labels: 📬 API, 🐞 BugFix

#30 refactor(login): modify login/register logic for the current
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RefreshTokenController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Models/Member.php
  app/Models/Post.php
  composer.json
  composer.lock
  config/auth.php
Labels: 📬 API, 🔨 Refactor

#31 feat(controller): Add authority and password fields to create new member
  app/Http/Controllers/CommitteeMemberController.php
  app/Http/Controllers/MemberController.php
  app/Http/Controllers/UserController.php
  app/Models/Member.php
  routes/api.php
Labels: 📬 API, ✨ Feature

#32 feature(admin): implement isAdmin method , modify getMember method
  app/Http/Controllers/CommitteeController.php
  app/Http/Controllers/MemberController.php
  app/Models/CommitteeMember.php
  routes/api.php
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#33 refactor(logout): modify removing token method
  app/Http/Controllers/Auth/LogoutController.php
Labels: 📬 API, 🔨 Refactor

#35 feat(member): implement return user profile method
  app/Http/Controllers/MemberController.php
  routes/api.php
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#36 fix(SeminarController): fix validation rules for string lengths
  app/Http/Controllers/SeminarController.php
Labels: 🐞 BugFix

#38 Implement multiple deletion, refactor AdminMiddleware to use JWT authentication
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/CommitteeMemberController.php
  app/Http/Controllers/FileController.php
  app/Http/Controllers/MemberController.php
  app/Http/Middleware/AdminMiddleware.php
  app/Models/CommitteeMember.php
  app/Models/Member.php
  database/migrations/2023_09_07_024420_add_default_value_to_note_column_in_members_table.php
  database/migrations/2023_09_07_024549_add_default_value_to_note_column_in_committee_members_table.php
  database/migrations/2023_09_09_103908_alter_columns_of_members_table.php
  routes/api.php
Labels: 📬 API, ✨ Feature, 🔨 Refactor, 🐞 BugFix

#39 ci: GitHub Actions for CI testing4
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/LogoutController.php
  app/Http/Controllers/Auth/RefreshTokenController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/CommitteeController.php
  app/Http/Controllers/CommitteeMemberController.php
  app/Http/Controllers/FileController.php
  app/Http/Controllers/MemberController.php
  app/Http/Controllers/SeminarController.php
  app/Http/Controllers/UserController.php
  app/Http/Middleware/AdminMiddleware.php
  app/Models/CommitteeMember.php
  app/Models/Member.php
  app/Models/Post.php
  app/Models/User.php
  composer.json
  composer.lock
  config/auth.php
  database/migrations/2023_09_05_122358_drop_users_table.php
  database/migrations/2023_09_05_122626_add_columns_members_table.php
  database/migrations/2023_09_07_024420_add_default_value_to_note_column_in_members_table.php
  database/migrations/2023_09_07_024549_add_default_value_to_note_column_in_committee_members_table.php
  database/migrations/2023_09_09_103908_alter_columns_of_members_table.php
  routes/api.php
Labels: 🌏 Deploy

#43 feat(controller): add custom request validation method
  app/Http/Controllers/CommitteeController.php
  app/Http/Controllers/CommitteeMemberController.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/MemberController.php
Labels: 📬 API, ✨ Feature, 🐞 BugFix
